#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile screen_name (or @screen_name)")
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # get_user_timeline    
    list_tweets = get_user_timeline(sys.argv[1])

    # analyze tweets
    score = 0
    for tweet in list_tweets:
    
        score = analyzer.analyze(tweet)
        
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))

        score = 0
    print (len(list_tweets))

if __name__ == "__main__":
    main()

